// Read-side helpers for the WSL wikivoyage feature.
// Reads the bundled JSON snapshot generated by scripts/ingest-wikivoyage.ts.
// Falls back to an empty dataset if the snapshot doesn't exist yet so
// the build never fails — pages render an empty-state.

import { cache } from "react";
import { promises as fs } from "node:fs";
import path from "node:path";
import type { WikivoyageDataset, WikivoyageEntry } from "./types";

const SNAPSHOT = path.resolve(process.cwd(), "public/data/wikivoyage-countries.json");

export const getWikivoyageDataset = cache(async (): Promise<WikivoyageDataset> => {
  try {
    const raw = await fs.readFile(SNAPSHOT, "utf8");
    return JSON.parse(raw) as WikivoyageDataset;
  } catch {
    return { generatedAt: "", count: 0, entries: [] };
  }
});

export async function getWikivoyageBySlug(slug: string): Promise<WikivoyageEntry | null> {
  const ds = await getWikivoyageDataset();
  return ds.entries.find((e) => e.slug === slug) ?? null;
}

export async function getWikivoyageByRegion(): Promise<Record<string, WikivoyageEntry[]>> {
  const ds = await getWikivoyageDataset();
  const out: Record<string, WikivoyageEntry[]> = {};
  for (const e of ds.entries) {
    (out[e.region] ??= []).push(e);
  }
  for (const r of Object.keys(out)) out[r].sort((a, b) => a.title.localeCompare(b.title));
  return out;
}
